CHANGELOG.md
example/lib/main.dart
ios/Classes/AudioRecorder.swift
ios/Classes/SwiftAudioWaveformsPlugin.swift
ios/Classes/Utils.swift
lib/src/controllers/recorder_controller.dart
pubspec.yaml

🐛  Fixed ios resume recording issue

---

CHANGELOG.md
android/src/main/kotlin/com/simform/audio_waveforms/AudioRecorder.kt
example/android/app/src/main/AndroidManifest.xml
example/lib/main.dart
example/pubspec.yaml
lib/src/audio_waveforms.dart
lib/src/controllers/player_controller.dart
lib/src/controllers/recorder_controller.dart

Fixed #50 android build error fixed & Fixed #41 upgraded flutter to 3.0

Fixed #50 android build error fixed & Fixed #41 upgraded flutter to 3.0

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
example/android/gradle/wrapper/gradle-wrapper.properties

Solve https://github.com/SimformSolutionsPvtLtd/audio_waveforms/issues/41#issuecomment-1151535833

Bump compileSdkVersion/gradle/kotlin to match flutter 3.0

---

CHANGELOG.md
example/lib/main.dart
lib/src/audio_waveforms.dart
lib/src/controllers/recorder_controller.dart
lib/src/painters/recorder_wave_painter.dart
pubspec.yaml

:bug: Fixed push back distance wouldn't reset when recording again

---

CHANGELOG.md
android/src/main/kotlin/com/simform/audio_waveforms/AudioRecorder.kt
android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
android/src/main/kotlin/com/simform/audio_waveforms/Utils.kt
example/lib/main.dart
ios/Classes/AudioRecorder.swift
ios/Classes/SwiftAudioWaveformsPlugin.swift
ios/Classes/Utils.swift
lib/src/base/audio_waveforms_interface.dart
lib/src/base/constants.dart
lib/src/controllers/recorder_controller.dart

Added bitrate functionality.
old request is below, please discard old one as it has some changes related to flutter 3 but new one has only changes related to bitrate functionality.
https://github.com/SimformSolutionsPvtLtd/audio_waveforms/pull/53

Added bitrate selection

---

CHANGELOG.md
lib/src/controllers/player_controller.dart
pubspec.yaml

:wrench: Add missing import

---

CHANGELOG.md
lib/src/controllers/player_controller.dart

- Ignored warning of unnecessary import of typed_data
- Updated CHANGELOG.md

🔨 Fix:: Pana Score Fix

---

CHANGELOG.md
android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
lib/src/audio_file_waveforms.dart
lib/src/audio_waveforms.dart
lib/src/base/utils.dart
lib/src/controllers/player_controller.dart
lib/src/controllers/recorder_controller.dart
pubspec.yaml

* Fixed zero duration would cause waveforms not to expand
* Fixed `postFrameCallback` error for flutter version below 3.0.0
* Updated default values for bitRate and sampleRate
Fixes #101

:bug: Fixed android volume error 

---

CHANGELOG.md
android/src/main/kotlin/com/simform/audio_waveforms/AudioRecorder.kt
example/lib/main.dart
ios/Classes/AudioRecorder.swift
lib/src/audio_waveforms.dart
lib/src/base/utils.dart
lib/src/base/wave_style.dart
lib/src/controllers/recorder_controller.dart
lib/src/painters/recorder_wave_painter.dart
pubspec.yaml

Updated default values for sample rate and bit rate.

:sparkles: Update recorder normalization 

---

android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt
android/src/main/kotlin/com/simform/audio_waveforms/WaveformExtractor.kt
example/lib/chat_bubble.dart
example/lib/main.dart
ios/Classes/AudioPlayer.swift
lib/src/controllers/player_controller.dart

:bug: Fix path with space doesn't doesn't show waveform

---

CHANGELOG.md
android/src/main/kotlin/com/simform/audio_waveforms/AudioRecorder.kt
android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
android/src/main/kotlin/com/simform/audio_waveforms/Utils.kt
example/lib/chat_bubble.dart
example/lib/main.dart
ios/Classes/AudioRecorder.swift
ios/Classes/SwiftAudioWaveformsPlugin.swift
ios/Classes/Utils.swift
lib/src/base/audio_waveforms_interface.dart
lib/src/base/constants.dart
lib/src/controllers/player_controller.dart
lib/src/controllers/recorder_controller.dart
pubspec.yaml

:sparkles: Add legacy normalization and updated minor stopAllPlayer behaviour

---

CHANGELOG.md
README.md
android/src/main/kotlin/com/simform/audio_waveforms/AudioRecorder.kt
android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
android/src/main/kotlin/com/simform/audio_waveforms/Utils.kt
example/lib/main.dart
lib/src/base/audio_waveforms_interface.dart
lib/src/base/constants.dart
lib/src/controllers/recorder_controller.dart

:sparkles: Added onRecorderStateChanged stream, onCurrentDuration stream and recordedDuration to get recorded duration for android

---

CHANGELOG.md
README.md
ios/Classes/AudioRecorder.swift
lib/src/audio_file_waveforms.dart
lib/src/controllers/recorder_controller.dart

:sparkles: Added recordedDuration to get recorded duration for ios and added onRecordingEnded stream

---

CHANGELOG.md
README.md
android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt
android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
android/src/main/kotlin/com/simform/audio_waveforms/Utils.kt
ios/Classes/AudioPlayer.swift
ios/Classes/SwiftAudioWaveformsPlugin.swift
ios/Classes/Utils.swift
lib/src/base/audio_waveforms_interface.dart
lib/src/base/constants.dart
lib/src/base/utils.dart
lib/src/controllers/player_controller.dart

:sparkles: Allow users to update reported duration for smoothening wave progress animation

---

example/ios/Runner/Info.plist
example/lib/main.dart
ios/Classes/AudioPlayer.swift
ios/Classes/AudioRecorder.swift

This PR fixes #165. Also adds error description for functions.

fix: :bug: IOS Recorder without path not working

---

android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt
android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
android/src/main/kotlin/com/simform/audio_waveforms/Utils.kt
ios/Classes/AudioPlayer.swift
ios/Classes/SwiftAudioWaveformsPlugin.swift
ios/Classes/Utils.swift
lib/src/base/audio_waveforms_interface.dart
lib/src/base/constants.dart
lib/src/controllers/player_controller.dart

The ability to set the audio speed (rate) #195

Implement audio speed

---

CHANGELOG.md
pubspec.yaml

Update change log and update package version

Update change log and update package version

---

lib/src/controllers/player_controller.dart

https://github.com/flutter/flutter/issues/148983

Use the `shortHash` of the key instead of `toString()`

---

CHANGELOG.md
analysis_options.yaml
android/build.gradle
android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
example/android/app/build.gradle
example/ios/Runner/AppDelegate.swift
lib/audio_waveforms.dart
lib/src/audio_file_waveforms.dart
lib/src/audio_waveforms.dart
lib/src/base/platform_streams.dart
lib/src/base/utils.dart
lib/src/controllers/player_controller.dart
pubspec.yaml

Update flutter and dart version

Update flutter and dart version

---

pubspec.yaml

Upgrade package version

---

CHANGELOG.md
analysis_options.yaml
example/pubspec.yaml
pubspec.yaml

- Downgrade flutter_lint version to support flutter version 3.10.x

🩹 Downgrade flutter_lint version 

---

CHANGELOG.md
example/pubspec.yaml
ios/Classes/AudioPlayer.swift
ios/Classes/SwiftAudioWaveformsPlugin.swift
lib/src/base/audio_waveforms_interface.dart
lib/src/controllers/player_controller.dart

fix: 🩹 iOS audio plays without sound (#349)

---

ios/Classes/SwiftAudioWaveformsPlugin.swift

This reverts commit d228db49e23c9c773e320622bc8649ce0703f90e.

Revert "fix: ✏️ remove extra quote (#361)"

---

CHANGELOG.md
example/lib/chat_bubble.dart
example/lib/main.dart
lib/src/audio_file_waveforms.dart
lib/src/painters/player_wave_painter.dart

- seekTo position issue where onDrag of waveform at initial position first wave outside the seekLine

fix: 🐛 seekTo position issue where onDrag of waveform first-wave outside the seekLine

---

CHANGELOG.md
lib/src/audio_file_waveforms.dart
lib/src/controllers/recorder_controller.dart

feat:✨ Provide a callback of drag,tap,start and end details on user gesture

---

CHANGELOG.md
ios/Classes/AudioRecorder.swift
ios/Classes/RecordingSettings.swift
ios/Classes/SwiftAudioWaveformsPlugin.swift
ios/Classes/Utils.swift
lib/src/base/audio_waveforms_interface.dart
lib/src/base/constants.dart
lib/src/controllers/recorder_controller.dart

fix: 🐛 Added support for Ios Linear PCM Codec

---

README.md

chore: 📝 Fix readme typo

---

lib/src/painters/recorder_wave_painter.dart

fix: 🐛 Fix left most visible wave is clipped in half when recording

---

CHANGELOG.md
README.md
android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
android/src/main/kotlin/com/simform/audio_waveforms/Utils.kt
example/ios/Podfile
ios/Classes/SwiftAudioWaveformsPlugin.swift
ios/Classes/Utils.swift
ios/Classes/WaveformExtractor.swift
lib/src/base/audio_waveforms_interface.dart
lib/src/base/constants.dart
lib/src/controllers/player_controller.dart

Add stopExtraction method for PlayerController to stop ongoing extraction in ios
Make Waveform extraction asynchronous

chore: ✨Add stop extraction method and asynchronous working for waveform extraction in ios

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
example/android/gradle/wrapper/gradle-wrapper.properties
example/pubspec.yaml

[chore: ⬆️ Upgrade gradle version](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/commit/ff8cf333d73089d8438c0abd5b9e02ecbfcd6fd5)
Upgrading gradle version because plugin is not able to sync project when opening in android folder
[chore: 🔨Remove unnecessary library](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/commit/c888e67379f3d6737c0e26cc45fafaa33f120992)
Removing because library is not used and also fixes #315

Upgrade gradle version and Remove unnecessary library

---

CHANGELOG.md
ios/Classes/WaveformExtractor.swift

chore: ⚡️ Preemptively add try catch for AVAudioFile initialization
