SimformSolutionsPvtLtd/audio_waveforms

- lib/src/controllers/player_controller.dart
Currently on iOS, using a path with the `file://` prefix causes an exception. In this commit, I used the `Uri` to obtain the path of the recording file uniformly. relate #35
> Fixed an issue with `preparePlayer` reporting `Please provide a valid file path` when the path has `file://` prefix on ios.

- CHANGELOG.md
- README.md
- android/src/main/kotlin/com/simform/audio_waveforms/Utils.kt
- lib/src/audio_file_waveforms.dart
- lib/src/base/audio_waveforms_interface.dart
- lib/src/base/platform_streams.dart
- lib/src/controllers/player_controller.dart
- pubspec.yaml
Fixes #137 and partially fixes 145
> :sparkles: Add onCompletion stream :bug: The visualization gets stuck incomplete.

- android/src/main/kotlin/com/simform/audio_waveforms/AudioRecorder.kt
- android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
- android/src/main/kotlin/com/simform/audio_waveforms/Utils.kt
- lib/src/base/audio_waveforms_interface.dart
- lib/src/base/constants.dart
- lib/src/controllers/recorder_controller.dart
fix:Failed to stop recording due to RecorderController dispose release MetaDataRetriever.
RecorderController invoke dispose method,go to this page again,invoke stop recording method,invoke mediaMetadataRetriever. setDataSource,occur no retriever available error.
> fix:Failed to stop recording #163

- CHANGELOG.md
- lib/src/controllers/player_controller.dart
- lib/src/controllers/recorder_controller.dart
- pubspec.yaml
> :bug: Do not call `notifyListeners()` when disposed

- lib/src/audio_file_waveforms.dart
- lib/src/audio_waveforms.dart
- lib/src/base/utils.dart
- lib/src/base/wave_clipper.dart
> :bug: Fixed last wave flickering and minor docs update

- android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt
- android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
- android/src/main/kotlin/com/simform/audio_waveforms/Utils.kt
- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- ios/Classes/AudioPlayer.swift
- ios/Classes/SwiftAudioWaveformsPlugin.swift
- ios/Classes/Utils.swift
- lib/src/base/audio_waveforms_interface.dart
- lib/src/base/constants.dart
- lib/src/controllers/player_controller.dart
Enhancement - implement audio player freed resource functionality.
> bugfix - 230/Stop player should not be freed the resources

- lib/src/audio_waveforms.dart
- lib/src/base/wave_style.dart
- lib/src/painters/player_wave_painter.dart
- lib/src/painters/recorder_wave_painter.dart
This PR adds conditions to rendering function so that it only renders when required. And also adds conditions to duration label list so that it doesn't add to many unnecessary labels.
Fixes #232
> fix: :bug: unnecessary rendering

- android/src/main/kotlin/com/simform/audio_waveforms/WaveformExtractor.kt
Fixed divison by zero due to duration value being rounded to 0 for audios under 1 second length. I changed the variable from duration (in seconds) to durationMillis which fixes an exception that was thrown.
```
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 39 pos 10: '<optimized out>'
```
> Fixed waveform for audios under 1 second not being extractable on Android

- android/src/main/kotlin/com/simform/audio_waveforms/AudioRecorder.kt
This bug happened when calling stop immediately after start (few hundred milliseconds max).
Fixed this by catching the RuntimeException from the MediaRecorder stop call and returning null for path and -1 for duration.
```
E/flutter ( 9041): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, null, null, java.lang.IllegalStateException
E/flutter ( 9041): 	at android.media.MediaRecorder.getMaxAmplitude(Native Method)
E/flutter ( 9041): 	at com.simform.audio_waveforms.AudioRecorder.getDecibel(AudioRecorder.kt:35)
E/flutter ( 9041): 	at com.simform.audio_waveforms.AudioWaveformsPlugin.onMethodCall(AudioWaveformsPlugin.kt:68)
E/flutter ( 9041): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258) …
```
> Stopping a recording immediately after starting it throws multiple exceptions on Android

- android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt
- android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
- android/src/main/kotlin/com/simform/audio_waveforms/Utils.kt
- example/pubspec.yaml
- ios/Classes/AudioPlayer.swift
- ios/Classes/SwiftAudioWaveformsPlugin.swift
- ios/Classes/Utils.swift
- lib/src/audio_waveforms.dart
- lib/src/base/utils.dart
- lib/src/controllers/player_controller.dart
- lib/src/controllers/recorder_controller.dart
- pubspec.yaml
> Upgrade the flutter version 

- ios/Classes/AudioRecorder.swift
Currently the checkHasPermission function will return before the user has confirmed or deny permissions. These small changes allow the future to return the proper value.
This allows auto start on iOS to work similar to Android.
> Auto start permission on iOS by waiting for response after user confirms or denies

- lib/src/controllers/player_controller.dart
Currently the dispose method will remove the platform instance if there is still one player currently activate.
Wait until all players are being disposed to remove the platform instance.
> Only dispose of instance if all playerKeys are removed

- lib/src/controllers/player_controller.dart
stopAllPlayers is an async method, but the return type does not have a Future. This means calling this method cannot be awaited.
> Fix return type for stopAllPlayers on PlayerController

- android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt
- ios/Classes/AudioPlayer.swift
Currently because there is a delay for updating the current duration of the player there is an inaccuracy when a player is paused or stopped because the update loop has stopped.
Update the current duration whenever the player state changes.
> Send current duration when seeked, paused, or stopped

- lib/src/controllers/player_controller.dart
This PR fix [200](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/issues/200).
> fix: 🐛 Enable seek gesture in paused mode

- CHANGELOG.md
- lib/src/audio_waveforms.dart
- pubspec.yaml
> 🩹 bugfix - 350 - Waveform clipping at starting position

- android/src/main/kotlin/com/simform/audio_waveforms/AudioRecorder.kt
- android/src/main/kotlin/com/simform/audio_waveforms/Utils.kt
- ios/Classes/AudioRecorder.swift
- ios/Classes/Utils.swift
- lib/src/base/audio_waveforms_interface.dart
- lib/src/base/constants.dart
- lib/src/controllers/recorder_controller.dart
Update return type of data from native to flutter
> update return type of result when user stop the audio player

- CHANGELOG.md
- android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt
- android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
- example/pubspec.yaml
> fix: 🐛 Cannot catch error of preparePlayer (#301)

- CHANGELOG.md
- README.md
- android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt
- android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
- android/src/main/kotlin/com/simform/audio_waveforms/Utils.kt
- example/lib/chat_bubble.dart
- ios/Classes/AudioPlayer.swift
- ios/Classes/SwiftAudioWaveformsPlugin.swift
- ios/Classes/Utils.swift
- lib/src/base/audio_waveforms_interface.dart
- lib/src/base/constants.dart
- lib/src/base/utils.dart
- lib/src/controllers/player_controller.dart
BugFix - 228 - Add setRelease Mode as per the requirement
> bugfix - 228 - add setReleaseMode method for manage player state

- CHANGELOG.md
- README.md
- android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt
- android/src/main/kotlin/com/simform/audio_waveforms/AudioRecorder.kt
- android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
- android/src/main/kotlin/com/simform/audio_waveforms/Utils.kt
- ios/Classes/AudioPlayer.swift
- ios/Classes/SwiftAudioWaveformsPlugin.swift
- ios/Classes/Utils.swift
- lib/src/base/audio_waveforms_interface.dart
- lib/src/base/constants.dart
- lib/src/controllers/player_controller.dart
- pubspec.yaml
Fixed [325](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/issues/325)
> feat: ✨ Add a method to pause all players at once

- CHANGELOG.md
- android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt
- android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
- android/src/main/kotlin/com/simform/audio_waveforms/WaveformExtractor.kt
- ios/Classes/AudioPlayer.swift
> fix: 🐛 Fix calling preparePlayer again does not cancel old waveform extraction

- CHANGELOG.md
- README.md
- example/lib/chat_bubble.dart
- lib/src/audio_file_waveforms.dart
- lib/src/controllers/player_controller.dart
- lib/src/controllers/waveform_extraction_controller.dart
Add WaveformExtractionController and migrate below methods and getters into it.
- waveformData
- onCurrentExtractedWaveformData
- onExtractionProgress
- extractWaveformData()
- stopWaveformExtraction()
> feat: ✨Add waveform extraction controller

- android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt
- ios/Classes/AudioPlayer.swift
Issue:
Awaiting PlayerController's setFinishMode on Flutter side never resolves, causing the app to hang.
Current behavior:
```dart
await playerController.setFinishMode(finishMode: FinishMode.pause);
print('Stop audio playback'); // Never resolves without calling result on native side
```
Expected behavior:
```dart
await playerController.setFinishMode(finishMode: FinishMode.pause);
print('Stop audio playback'); // Executes after method completes
```
> fix: 🐛️ call result in setFinishMode to resolve Flutter Future

- CHANGELOG.md
- android/src/main/kotlin/com/simform/audio_waveforms/Utils.kt
- android/src/main/kotlin/com/simform/audio_waveforms/WaveformExtractor.kt
- pubspec.yaml
> fix: 🐛️ Waveform extraction stuck at 99%

- CHANGELOG.md
- android/src/main/kotlin/com/simform/audio_waveforms/WaveformExtractor.kt
This PR tries to fix #375 and #376
> chore: ⚡️️ Preemptively account for invalid input buffer and 🐛 don't send error if already sent
